<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.DWBH21</groupId>
    <artifactId>aarithmetic</artifactId>
    <version>1.0</version> 
    <packaging>jar</packaging>   

    <name>Arbitrary Precision Arithmetic Class in Java</name>
    <description>Implementation of an infinite/arbitrary-precision arithmetic library in Java
using OOP concepts. Final Project for CS1023 IITH</description>
    <url>https://github.com/DWBH21/Project1.git</url>

    <developers>
        <developer>
            <id>DWBH21</id>
            <name>Anant Maheshwary</name>
            <email>anant.maheshwary@gmail.com</email>
        </developer>
    </developers>

    <build>
        <finalName>aarithmetic</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.0</version>
                <configuration>
                    <source>21</source>
                    <target>21</target>     
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>